# Generated by Django 5.0.3 on 2024-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WARMUP', 'Warmup'), ('OWN_BODY_WEIGHT', 'Own Body Weight')], max_length=100)),
                ('muscle_group', models.CharField(choices=[('UPPER_BODY', 'Upper Body'), ('LOWER_BODY', 'Lower Body'), ('ABS', 'Abs'), ('BACK', 'Back')], max_length=100)),
                ('experience_level', models.CharField(choices=[('NEW', 'New'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced'), ('PROFESSIONAL', 'Professional')], max_length=100)),
                ('duration', models.IntegerField()),
                ('calories_burnt', models.IntegerField()),
                ('drawablepicname', models.CharField(max_length=255)),
            ],
        ),
    ]
