# Generated by Django 5.0.3 on 2024-05-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testing', '0004_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cardiovascular_d', models.BooleanField(default=False)),
                ('bad_knee', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('osteoporosis', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
    ]
