# Generated by Django 5.0.3 on 2024-05-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWorkoutHistory',
        ),
    ]
